version: "3.8"
services:
  app:
    build:
      context: ./frontend
    volumes:
      - .:/frontend
    ports:
      - 3000:3000
    image: app:nuri-frontend
    container_name: nuri_container
    command: npm start